Devirtualize WorldImpl::size and rank
TESSEorg/ttg pull request #186
Opened 2021-10-29 16:33 UTC by devreal

Also avoid MPI calls in the PaRSEC backend (I was sure I had fixed that somewhere...)

Signed-off-by: Joseph Schuchart <schuchart@icl.utk.edu>

2021-11-01 14:59 UTC, therault approved these changes

2021-11-08 18:23 UTC, evaleev requested changes

2021-11-08 19:47 UTC, devreal commented
@evaleev Done, please check again. This is only for base classes so it shouldn't concern users.

2021-11-09 08:41 UTC, evaleev approved these changes

2021-11-09 08:41 UTC, merged