Ashawini27/fix/add debug capabilities
TESSEorg/ttg pull request #219
Opened 2022-02-17 22:25 UTC by Ashawini27

Add debug capabilities to unit tests

2022-02-17 22:29 UTC, devreal commented
LGTM :+1:  It would be nice to have that functionality as part of a function/macro that we can drop into all our tests to enable debugging if `TTG_DEBUGGER` (or `TTG_ENABLE_DEBUGGER`?) is set.

2022-02-24 13:47 UTC, evaleev requested changes

2022-02-24 13:47 UTC, evaleev commented on README.md
> +- If xterm already installed then set "Environment Variable" to /TTG_DEBUGGER=gdb_xterm/lldb_xterm based on the type of compiler system hold to run debugger for parallelly executing processes
```suggestion
- If an X11 server is running (check if environment variable `DISPLAY` is set), then set environment variable `TTG_DEBUGGER` to {`gdb_xterm`,`lldb_xterm`} to launch {`gdb`,`lldb`} upon receiving a signal like `SIGSEGV` or `SIGABRT` (one `xterm` window per rank will be created);
- If an X11 server is not running the set `TTG_DEBUGGER` to empty value; upon receiving a signal the program will print instructions for how to attach a debugger to a running process from another terminal. 
```

2022-02-24 13:47 UTC, evaleev commented on README.md
> +![Build Status](https://github.com/TESSEorg/ttg/workflows/CMake/badge.sv)
this change seems to be not intended, revert

2022-03-02 20:34 UTC, evaleev approved these changes

2022-03-02 20:35 UTC, merged