Minor improvements to the documentation
TESSEorg/ttg pull request #292
Opened 2024-06-11 14:30 UTC by devreal

2024-06-11 17:19 UTC, nileshchat commented on README.md
> +While it is possible to use a specific TTG backend explicitly, by using the appropriate namespaces, it is recommended to write backend-neutral programs that can be specialized to a particular backend
... in **one* of **the* two ways

2024-06-11 17:28 UTC, nileshchat commented on README.md
> +`ttg::execute()` must occur before, not after, sending any messages. Note also that we must ensure that only one such message is generated. Since TTG execution uses the Single Program Multiple Data (
~Otherwise~ ?

2024-06-11 17:40 UTC, nileshchat commented on README.md
> +For optimal performance, the low-level runtime that manages the data motion across the memory hierarchy (host-to-host (i.e., between MPI ranks), host-to-device, and device-to-device) and so it must b
... and so ~it~ **on*, must be able to ~_track_~ **track* / `_track_` each datum as it orchestrates the computation. For example, when a TTG task ~`send`'s~ sends a datum ...

2024-06-11 20:33 UTC, evaleev requested changes

2024-06-11 20:33 UTC, evaleev commented on README.md
> +  // add a single task into the taskpool
since we never introduce implementation details like taskpools, I prefer something like `// create task to kickstart computation`

2024-06-11 20:33 UTC, evaleev commented on README.md
> +  // initialization
can just skip comments that look like code

2024-06-11 20:33 UTC, evaleev commented on README.md
> +  // finalization
can just skip comments that look like code

2024-06-11 20:33 UTC, evaleev commented on README.md
> +  const int64_t N = 20; // want to compute Fib(20)
should match the TT name, so `Fib` -> `fib`

2024-06-11 20:33 UTC, evaleev commented on README.md
> +  ttg::Edge<int64_t, Fn> f2f; // Fib to Fib
fib -> fib

2024-06-11 20:33 UTC, evaleev commented on README.md
> +  ttg::Edge<void, Fn> f2p;    // Fib to print
fib -> print

2024-06-11 20:33 UTC, evaleev commented on README.md
> +If no pointer is passed to the constructor of `Buffer<T>` the buffer becomes owning, i.e., it allocates the necessary host-side memory.
do we need to get in the weeds of why `F` must be on heap to give relocatability?

2024-06-11 20:33 UTC, evaleev commented on README.md
> +will be discussed in [manuscript ``Generalized Flow-Graph Programming Using Template Task-Graphs: Initial Implementation and Assessment''](https://www.ipdps.org/ipdps2022/2022-accepted-papers.html) a
"will be" -> "is"

2024-06-18 12:38 UTC, evaleev commented
@devreal ping

2025-01-16 18:33 UTC, abouteiller approved these changes

2025-01-16 18:33 UTC, abouteiller commented on README.md
> +`ttg::execute()` must occur before, not after, sending any messages. Note also that we must ensure that only one such message is generated. Since TTG execution uses the Single Program Multiple Data (
Is it actually required that the first process (rank 0) initiates, or that `only one process (rank) gets to send the message`

2025-01-16 18:33 UTC, abouteiller commented on README.md
> +is discussed in [manuscript ``Generalized Flow-Graph Programming Using Template Task-Graphs: Initial Implementation and Assessment''](https://www.ipdps.org/ipdps2022/2022-accepted-papers.html) and ha
don't you have a full DOI at this point for this?

2025-01-16 18:33 UTC, abouteiller commented on README.md
> +  // make sure the graph is connected (simple for a single node)
this is not sufficient to understand why the graph needs to be connected, or why it is simple for a single node.

2025-01-23 19:10 UTC, devreal commented on README.md
> +`ttg::execute()` must occur before, not after, sending any messages. Note also that we must ensure that only one such message is generated. Since TTG execution uses the Single Program Multiple Data (
This text is not correct. Every process must call `ttg::execute()`.

2025-05-23 02:52 UTC, evaleev requested changes
added proposed changes that address pending requests/comments

2025-05-23 02:52 UTC, evaleev commented on README.md
> +  // make sure the graph is connected (simple for a single node)
```suggestion
  // single TT is also a TT graph (=TTG); signal that we are done constructing the TTG
```

2025-05-23 02:52 UTC, evaleev commented on README.md
> +While it is possible to use a specific TTG backend explicitly, by using the appropriate namespaces, it is recommended to write backend-neutral programs that can be specialized to a particular backend
```suggestion
While it is possible to use a specific TTG backend explicitly, by using the appropriate namespaces, it is recommended to write backend-neutral programs that can be specialized to a particular backend in of the two ways.
```

2025-05-23 02:52 UTC, evaleev commented on README.md
> +  // a simple template task
```suggestion
  // a simple template task (TT)
```

2025-05-23 02:52 UTC, evaleev commented on README.md
>  ## Specify a TTG
```suggestion
## Create a TTG
```

2025-05-23 02:52 UTC, evaleev commented on README.md
> +To make a TTG, create and connect one or more TTs. The simplest TTG consists of a single TT as in the hello-world example.
```suggestion
To make a TTG, create and connect one or more TTs. The simplest TTG consists of a single TT as in the "Hello, World!" example.
```

2025-05-23 02:52 UTC, evaleev commented on README.md
> +The "Hello, World!" example contains a single TT that executes a single task (hence, task ID can be omitted, i.e., `void`) that does not take and produce any data. The easiest way to make such a TT
```suggestion
Since the TT in the "Hello, World!" example generates a single task, the task ID can be omitted (its type is `void`). This task also does not take or produce any data. The easiest way to make such a TT  is by wrapping a callable (e.g., a lambda) with `ttg::make_tt`:
```

2025-05-23 02:52 UTC, evaleev commented on README.md
> +`ttg::execute()` must occur before, not after, sending any messages. Note also that we must ensure that only one such message is generated. Since TTG execution uses the Single Program Multiple Data (
```suggestion
`ttg::execute()` starts the TTG work engines and must occur before, not after, kickstarting off any computation by sending the data into the free in-terminals. The kickstart messages are generated by invoking `TT::invoke(taskID, values)`; in this case the task ID is void, and the task does not take any input data, so `TT::invoke()` receivesno parameters. Since TTG uses the Single Program Multiple Data (SPMD) execution model, every process invokes `ttg::execute()` when this TTG program is invoked as multiple processes, but only the first process (rank) gets to send the kickstart message since all messages in a TTG program, including the kickstart messages, must be unique.
```

2025-05-23 02:52 UTC, evaleev commented on README.md
> +`ttg::execute()` must occur before, not after, sending any messages. Note also that we must ensure that only one such message is generated. Since TTG execution uses the Single Program Multiple Data (
The "only some processes" referred to invoke, not execute. I rephrased.

2025-05-23 02:52 UTC, evaleev commented on README.md
> +is discussed in [manuscript ``Generalized Flow-Graph Programming Using Template Task-Graphs: Initial Implementation and Assessment''](https://www.ipdps.org/ipdps2022/2022-accepted-papers.html) and ha
```suggestion
was discussed in manuscripts [``Generalized Flow-Graph Programming Using Template Task-Graphs: Initial Implementation and Assessment''](https://doi.org/10.1109/IPDPS53621.2022.00086) and [``Composition of Algorithmic Building Blocks in Template Task Graphs''](https://doi.org/10.1109/PAW-ATM56565.2022.00008). Low-level benchmarking of TTG tasking was reported in manuscript [``Pushing the Boundaries of Small Tasks: Scalable Low-Overhead Data-Flow Programming in TTG''](https://doi.org/10.1109/CLUSTER51413.2022.00026). 
```

2025-05-23 02:54 UTC, evaleev commented
@devreal should be good after merging the proposed changes

2025-05-23 14:11 UTC, devreal commented
Thanks @evaleev 👍  Accepted the changes, rebased to fix some outdated CI packages. Will merge when CI is done.

2025-05-23 16:23 UTC, evaleev approved these changes

2025-05-23 16:23 UTC, merged